name: hotel-management

services:
  db:
    container_name: hotel-management-db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hotel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hotel}
      POSTGRES_DB: ${POSTGRES_DB:-hotel_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - hotel-db-data:/var/lib/postgresql/data
    networks:
      - hotel-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-hotel} -d ${POSTGRES_DB:-hotel_db}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    container_name: hotel-management-api
    restart: unless-stopped
    build:
      context: ../api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-hotel}:${POSTGRES_PASSWORD:-hotel}@db:5432/${POSTGRES_DB:-hotel_db}
      - DIRECT_URL=postgresql://${POSTGRES_USER:-hotel}:${POSTGRES_PASSWORD:-hotel}@db:5432/${POSTGRES_DB:-hotel_db}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hotel-net

  web:
    container_name: hotel-management-web
    restart: unless-stopped
    build:
      context: ../web
      dockerfile: Dockerfile
      args:
        API_INTERNAL_URL: http://api:4000
    depends_on:
      - api
    networks:
      - hotel-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: hotel-management-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://web:3000
    environment:
     - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - web
    networks:
      - hotel-net

networks:
  hotel-net:
    driver: bridge

volumes:
  hotel-db-data:
